### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by qcwolf** [IvonWei/flexget_qbittorrent_mod#1]
/volume1/@appstore/py3k/usr/local/bin/flexget/bin/flexget daemon start -d

2020-01-30 00:17 CRITICAL plugin                        Exception while loading plugin flexget.plugins.qbittorrent_mod
Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/bin/flexget/lib/python3.5/site-packages/flexget/plugin.py", line 434, in _import_plugin
    import_module(module_name)
  File "/volume1/@appstore/py3k/usr/local/bin/flexget/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 658, in exec_module
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 724, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/.config/flexget/plugins/qbittorrent_mod.py", line 305
    name_with_pieces_hashes = f'{name}:{pieces_hashes}'
                                                      ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/bin/flexget/bin/flexget", line 8, in <module>
    sys.exit(main())
  File "/volume1/@appstore/py3k/usr/local/bin/flexget/lib/python3.5/site-packages/flexget/__init__.py", line 47, in main
    manager.start()
  File "/volume1/@appstore/py3k/usr/local/bin/flexget/lib/python3.5/site-packages/flexget/manager.py", line 399, in start
    self.initialize()
  File "/volume1/@appstore/py3k/usr/local/bin/flexget/lib/python3.5/site-packages/flexget/manager.py", line 236, in initialize
    extra_components=[os.path.join(self.config_base, 'components')],
  File "/volume1/@appstore/py3k/usr/local/bin/flexget/lib/python3.5/site-packages/flexget/plugin.py", line 561, in load_plugins
    _load_plugins_from_dirs(extra_plugins)
  File "/volume1/@appstore/py3k/usr/local/bin/flexget/lib/python3.5/site-packages/flexget/plugin.py", line 481, in _load_plugins_from_dirs
    _import_plugin(module_name, plugin_path)
  File "/volume1/@appstore/py3k/usr/local/bin/flexget/lib/python3.5/site-packages/flexget/plugin.py", line 434, in _import_plugin
    import_module(module_name)
  File "/volume1/@appstore/py3k/usr/local/bin/flexget/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 658, in exec_module
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 724, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/.config/flexget/plugins/qbittorrent_mod.py", line 305
    name_with_pieces_hashes = f'{name}:{pieces_hashes}'
                                                      ^
SyntaxError: invalid syntax

**Comment by madwind** [comment]
name_with_pieces_hashes = f'{name}:{pieces_hashes}'
怎么看都没看出来这句哪里有问题 试试下最新版本覆盖再运行一次？

**Comment by madwind** [comment]
早上起来查了一下 原来f'{name}:{pieces_hashes}' 是python3.6才支持的语法 你的python版本是3.5所以报错了

**Comment by qcwolf** [comment]
感谢大神回复，群晖的python好像最高只有3.5.。。。。

**Comment by madwind** [comment]
我把它换掉好了 反正也只有这么一个地方 试试看 v0.1.7 的 能不能运行了

**Comment by qcwolf** [comment]
换了1.7还是无法启动

2020-01-30 13:42 WARNING  manager                       Your locale declares ascii as the filesystem encoding. Any plugins reading filenames from disk will not work properly for filenames containing non-ascii characters. Make sure your locale env variables are set up correctly for the environment which is launching FlexGet.
2020-01-30 13:42 CRITICAL plugin                        Plugin `flexget.plugins.qbittorrent_mod` failed to import dependencies
Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/bin/flexget/lib/python3.5/site-packages/flexget/plugin.py", line 434, in _import_plugin
    import_module(module_name)
  File "/volume1/@appstore/py3k/usr/local/bin/flexget/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/.config/flexget/plugins/qbittorrent_mod.py", line 7, in <module>
    from loguru import logger
ImportError: No module named 'loguru'
2020-01-30 13:42 WARNING  config_schema                 The clean_transmission plugin is deprecated. Configure a new task using the from_transmission plugin as well as the transmission plugin using the remove or purge action.
2020-01-30 13:42 ERROR    manager                       There does not appear to be a daemon running.
2020-01-30 13:42 WARNING  manager                       Your locale declares ascii as the filesystem encoding. Any plugins reading filenames from disk will not work properly for filenames containing non-ascii characters. Make sure your locale env variables are set up correctly for the environment which is launching FlexGet.
2020-01-30 13:42 CRITICAL plugin                        Plugin `flexget.plugins.qbittorrent_mod` failed to import dependencies
Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/bin/flexget/lib/python3.5/site-packages/flexget/plugin.py", line 434, in _import_plugin
    import_module(module_name)
  File "/volume1/@appstore/py3k/usr/local/bin/flexget/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/.config/flexget/plugins/qbittorrent_mod.py", line 7, in <module>
    from loguru import logger
ImportError: No module named 'loguru'

**Comment by madwind** [comment]
这个应该是你的flexget版本问题 翻了一下flexget的changelog 它是从3.0.19才开始使用loguru的
群晖也是可以用docker的吧, dockerhub有现成的flexget镜像 wiserain/flexget

**Comment by qcwolf** [comment]
感谢大神，成功启动了~群晖直接安装flexget不知道为什么升不了级。。。。

**Comment by qcwolf** [comment]
启动后 flexget 还有一条警告：The clean_transmission plugin is deprecated. Configure a new task using the from_transmission plugin as well as the transmission plugin using the remove or purge action.

**Comment by madwind** [comment]
这个是因为你的配置文件里写了clean_transmission 这个插件 这个插件现在已经叫做 from_transmission 了 如果你不用transmission 直接在webui的配置页里把源码里的config.yml粘贴进去 改一下就好了
