### ISSUE TITLE
签到报错  sign_in BUG: Unhandled error in plugin auto_sign_in: could not convert string to float: '-'

### ISSUE THREAD

**Issue by pengkaiwei** [IvonWei/flexget_qbittorrent_mod#126]
docker 部署的最新版本 madwind/flexget
插件也是最新版本

签到报错

CRITICAL
task
sign_in
BUG: Unhandled error in plugin auto_sign_in: could not convert string to float: '-'

错误log如下

```
2022-10-10 08:57:07 CRITICAL task          sign_in         BUG: Unhandled error in plugin auto_sign_in: could not convert string to float: '-'
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x1523eb405870>
    └ <Thread(task_queue, started daemon 23243655075584)>
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x1523eb4055a0>
    └ <Thread(task_queue, started daemon 23243655075584)>
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 23243655075584)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 23243655075584)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x1523d7c522c0>>
    └ <Thread(task_queue, started daemon 23243655075584)>
  File "/usr/local/lib/python3.10/site-packages/flexget/task_queue.py", line 47, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x1523e81e4a60>
    │    └ <flexget.task.Task object at 0x1523d5791f90>
    └ <flexget.task_queue.TaskQueue object at 0x1523d7c522c0>
  File "/usr/local/lib/python3.10/site-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x1523d5791f90>
           └ <function Task.execute at 0x1523e81e49d0>
  File "/usr/local/lib/python3.10/site-packages/flexget/task.py", line 727, in execute
    self._execute()
    │    └ <function Task._execute at 0x1523e81e4940>
    └ <flexget.task.Task object at 0x1523d5791f90>
  File "/usr/local/lib/python3.10/site-packages/flexget/task.py", line 696, in _execute
    self.__run_task_phase(phase)
    │                     └ 'output'
    └ <flexget.task.Task object at 0x1523d5791f90>
  File "/usr/local/lib/python3.10/site-packages/flexget/task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x1523d5791f90>, {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (...
               │                 │       └ 'output'
               │                 └ <PluginInfo(name=auto_sign_in)>
               └ <flexget.task.Task object at 0x1523d5791f90>
> File "/usr/local/lib/python3.10/site-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x1523d5791f90>, {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (...
             └ <Event(name=plugin.auto_sign_in.output,func=on_task_output,priority=128)>
  File "/usr/local/lib/python3.10/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x1523d5791f90>, {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (...
           │    └ <bound method PluginAutoSignIn.on_task_output of <flexget.plugins.auto_sign_in.PluginAutoSignIn object at 0x1523d8ee5300>>
           └ <Event(name=plugin.auto_sign_in.output,func=on_task_output,priority=128)>

  File "/config/plugins/auto_sign_in.py", line 88, in on_task_output
    DetailsReport().build(task)
    │                     └ <flexget.task.Task object at 0x1523d5791f90>
    └ <class 'flexget.plugins.ptsites.utils.details_report.DetailsReport'>

  File "/config/plugins/ptsites/utils/details_report.py", line 147, in build
    details_now[key] = self.transfer_data(key, value)
    │           │      │    │             │    └ '-'
    │           │      │    │             └ 'share_ratio'
    │           │      │    └ <function DetailsReport.transfer_data at 0x1523da0f6950>
    │           │      └ <flexget.plugins.ptsites.utils.details_report.DetailsReport object at 0x1523d58654b0>
    │           └ 'share_ratio'
    └ {'downloaded': 0.0, 'uploaded': 0.0}

  File "/config/plugins/ptsites/utils/details_report.py", line 269, in transfer_data
    return float(value)
                 └ '-'

ValueError: could not convert string to float: '-'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "/config/plugins/auto_sign_in.py", line 88, in on_task_output
    DetailsReport().build(task)
  File "/config/plugins/ptsites/utils/details_report.py", line 147, in build
    details_now[key] = self.transfer_data(key, value)
  File "/config/plugins/ptsites/utils/details_report.py", line 269, in transfer_data
    return float(value)
ValueError: could not convert string to float: '-'
```

辛苦大佬了！！！谢谢！

**Comment by madwind** [comment]
查找log 看哪个站的分享率是 '-'

**Comment by pengkaiwei** [comment]
> 查找log 看哪个站的分享率是 '-'

好像是qb,qb是新装的，没有下载数据

2022-10-10 10:56:00 INFO     flexget.plugins.ptsites.sites.qbittorrent                 site_name: qbittorrent, details: {'downloaded': '0 B', 'uploaded': '0 B', 'share_ratio': '-', 'points': 0, 'leeching': 0, 'seeding': 0, 'hr': 0}
2022-10-10 10:56:00 INFO     flexget.plugins.ptsites.executor                 site_name: qbittorrent, details: {'downloaded': '0 B', 'uploaded': '0 B', 'share_ratio': '-', 'points': 0, 'leeching': 0, 'seeding': 0, 'hr': 0}

**Comment by madwind** [comment]
更新插件试试

**Comment by pengkaiwei** [comment]
谢谢大佬 已经没有报错了！

**Comment by pengkaiwei** [comment]
> 谢谢大佬 已经没有报错了！

谢谢大佬 已经没有报错了！

> 更新插件试试

谢谢大佬 已经没有报错了！
