### ISSUE TITLE
AttributeError: 'QBittorrentClient' object has no attribute '_update_entry_trackers'

### ISSUE THREAD

**Issue by klchen0112** [IvonWei/flexget_qbittorrent_mod#2]
2020-03-20 07:07:34 CRITICAL task          modify          BUG: Unhandled error in plugin qbittorrent_mod: 'QBittorrentClient' object has no attribute '_update_entry_trackers'
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x14e859837ca0>
    └ <Thread(task_queue, started daemon 22988072200992)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x14e8598379d0>
    └ <Thread(task_queue, started daemon 22988072200992)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 22988072200992)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 22988072200992)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x14e855042e50>>
    └ <Thread(task_queue, started daemon 22988072200992)>
  File "/usr/lib/python3.8/site-packages/flexget/task_queue.py", line 45, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x14e857d78160>
    │    └ <flexget.task.Task object at 0x14e853a29220>
    └ <flexget.task_queue.TaskQueue object at 0x14e855042e50>
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 79, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x14e853a29220>
           └ <function Task.execute at 0x14e857d780d0>
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 696, in execute
    self._execute()
    │    └ <function Task._execute at 0x14e857d78040>
    └ <flexget.task.Task object at 0x14e853a29220>
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 662, in _execute
    self.__run_task_phase(phase)
    │                     └ 'output'
    └ <flexget.task.Task object at 0x14e853a29220>
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 488, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x14e853a29220>, {'host': '192.168.1.114', 'port': 8080, 'use_ssl': False, 'username': 'admin',...
               │                 │       └ 'output'
               │                 └ <PluginInfo(name=qbittorrent_mod)>
               └ <flexget.task.Task object at 0x14e853a29220>
> File "/usr/lib/python3.8/site-packages/flexget/task.py", line 521, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x14e853a29220>, {'host': '192.168.1.114', 'port': 8080, 'use_ssl': False, 'username': 'admin',...
             └ <Event(name=plugin.qbittorrent_mod.output,func=on_task_output,priority=135)>
  File "/usr/lib/python3.8/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x14e853a29220>, {'host': '192.168.1.114', 'port': 8080, 'use_ssl': False, 'username': 'admin',...
           │    └ <bound method PluginQBittorrentMod.on_task_output of <flexget.plugins.flexget_qbittorrent_mod.qbittorrent_mod.PluginQBittorre...
           └ <Event(name=plugin.qbittorrent_mod.output,func=on_task_output,priority=135)>
  File "/usr/lib/python3.8/site-packages/flexget/plugins/flexget_qbittorrent_mod/qbittorrent_mod.py", line 206, in on_task_output
    action(task, option)
    │      │     └ {'tag_by_tracker': True, 'replace_tracker': {'': 'https...
    │      └ <flexget.task.Task object at 0x14e853a29220>
    └ <bound method PluginQBittorrentMod.modify_entries of <flexget.plugins.flexget_qbittorrent_mod.qbittorrent_mod.PluginQBittorre...
  File "/usr/lib/python3.8/site-packages/flexget/plugins/flexget_qbittorrent_mod/qbittorrent_mod.py", line 424, in modify_entries
    self.client.edit_trackers(entry.get('torrent_info_hash'), orig_url, new_url)
    │    │      │             │     │                         │         └ ''
    │    │      │             │     │                         └ ''
    │    │      │             │     └ <function LazyDict.get at 0x14e857f9a0d0>
    │    │      │             └ <Entry(title=[EAC][130320] kz(livetune) feat. 初音ミク - Re-Dial[期間限定盤] (WAV+CUE+BK+MDF),state=accepted)>
    │    │      └ <function QBittorrentClient.edit_trackers at 0x14e85631f160>
    │    └ <qbittorrent_client.QBittorrentClient object at 0x14e85351adc0>
    └ <flexget.plugins.flexget_qbittorrent_mod.qbittorrent_mod.PluginQBittorrentMod object at 0x14e855118a30>
  File "/usr/lib/python3.8/site-packages/flexget/plugins/flexget_qbittorrent_mod/qbittorrent_client.py", line 238, in edit_trackers
    self._update_entry_trackers(torrent_hash)
    │                           └ '0c1d01a1f33b552eb929daf6fc966f6e0ffa2100'
    └ <qbittorrent_client.QBittorrentClient object at 0x14e85351adc0>

AttributeError: 'QBittorrentClient' object has no attribute '_update_entry_trackers'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 521, in __run_plugin
    result = method(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/flexget/plugins/flexget_qbittorrent_mod/qbittorrent_mod.py", line 206, in on_task_output
    action(task, option)
  File "/usr/lib/python3.8/site-packages/flexget/plugins/flexget_qbittorrent_mod/qbittorrent_mod.py", line 424, in modify_entries
    self.client.edit_trackers(entry.get('torrent_info_hash'), orig_url, new_url)
  File "/usr/lib/python3.8/site-packages/flexget/plugins/flexget_qbittorrent_mod/qbittorrent_client.py", line 238, in edit_trackers
    self._update_entry_trackers(torrent_hash)
AttributeError: 'QBittorrentClient' object has no attribute '_update_entry_trackers'

docker qbit 4.2.1
docker flexget 3.1.5
经常报错 有大量tag没有修改,大约有1000+

**Comment by madwind** [comment]
奇怪 不知道什么时候不小心删除了这个方法，添加回来了……更新一下就好
