### ISSUE TITLE
BUG: Unhandled error in plugin qbittorrent_mod: unsupported operand type(s)，作者自动删除命令提示这个咋办？是qbittorrent的问题吗？我装的是4.3.5版本的

### ISSUE THREAD

**Issue by 2375399351** [IvonWei/flexget_qbittorrent_mod#30]
作者自动删除命令提示这个咋办？是qbittorrent的问题吗？我装的是4.3.5版本的

**Comment by madwind** [comment]
贴log

**Comment by 2375399351** [comment]
2021-12-09 10:13:48 DEBUG    task_queue                    task delete aborted: TaskAbort(reason=BUG: Unhandled error in plugin qbittorrent_mod: unsupported operand type(s) for *: 'NoneType' and 'int', silent=False)
2021-12-09 10:15:15 DEBUG    manager                       New config data loaded.
2021-12-09 10:15:15 DEBUG    web_server_daemon                 web server config has'nt changed
2021-12-09 10:15:15 DEBUG    irc                           No irc connections defined in the config
2021-12-09 10:15:15 INFO     scheduler                     No schedules defined in config. Defaulting to run all tasks on a 1 hour interval.
2021-12-09 10:15:15 DEBUG    manager                       backing up old config to /config/config-211209101515.bak before new save
2021-12-09 10:15:19 DEBUG    status_api                    db has a total of 5 status tasks
2021-12-09 10:15:19 DEBUG    status.db                     querying status tasks: start=0, stop=10, order_by=last_execution_time, descending=True
2021-12-09 10:15:23 INFO     manager                       Config change detected. Reloading.
2021-12-09 10:15:23 DEBUG    manager                       config_name: config
2021-12-09 10:15:23 DEBUG    manager                       config_base: /config
2021-12-09 10:15:23 DEBUG    manager                       New config data loaded.
2021-12-09 10:15:23 DEBUG    web_server_daemon                 web server config has'nt changed
2021-12-09 10:15:23 DEBUG    irc                           No irc connections defined in the config
2021-12-09 10:15:23 INFO     scheduler                     No schedules defined in config. Defaulting to run all tasks on a 1 hour interval.
2021-12-09 10:15:23 INFO     manager                       Config successfully reloaded!
2021-12-09 10:15:23 DEBUG    task          delete          executing delete
2021-12-09 10:15:23 DEBUG    template      delete          Merging template from_qbittorrent_template into task delete
2021-12-09 10:15:23 DEBUG    template      delete          Merging template qbittorrent_base_template into task delete
2021-12-09 10:15:23 DEBUG    template      delete          Merging template qbittorrent_delete_keeper_template into task delete
2021-12-09 10:15:23 DEBUG    disable       delete          Disabled plugins: retry_failed, history, seen_info_hash, seen
2021-12-09 10:15:23 DEBUG    remember_rej  delete          Task config has changed since last run, purging remembered entries.
2021-12-09 10:15:23 DEBUG    backlog       delete          63 entries purged from backlog
2021-12-09 10:15:23 VERBOSE  details       delete          Produced 69 entries.
2021-12-09 10:15:23 DEBUG    sort_by       delete          sorting entries by: qbittorrent_last_activity
2021-12-09 10:15:23 DEBUG    if            delete          Serie.A.AS.Roma.vs.Inter.04.12.2021.1080i.HDTV.MPA2.0.H.264-playTV matched requirement qbittorrent_category in ['flexget'] and qbittorrent_last_activity < now - timedelta(days=2)
2021-12-09 10:15:23 VERBOSE  task          delete          ACCEPTED: `Serie.A.AS.Roma.vs.Inter.04.12.2021.1080i.HDTV.MPA2.0.H.264-playTV` by if plugin because matched requirement: qbittorrent_category in ['flexget'] and qbittorrent_last_activity < now - timedelta(days=2)
2021-12-09 10:15:23 DEBUG    urlrewriter   delete          Checking 1 entries
2021-12-09 10:15:23 VERBOSE  details       delete          Summary - Accepted: 1 (Rejected: 0 Undecided: 68 Failed: 0)
2021-12-09 10:15:23 DEBUG    flexget.plugins.qbittorrent_mod delete          Successfully connected to qBittorrent.
2021-12-09 10:15:23 CRITICAL task          delete          BUG: Unhandled error in plugin qbittorrent_mod: unsupported operand type(s) for *: 'NoneType' and 'int'
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x14ca4fd5c5e0>
    └ <Thread(task_queue, started daemon 22858945403696)>
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x14ca4fd5c310>
    └ <Thread(task_queue, started daemon 22858945403696)>
  File "/usr/local/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 22858945403696)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 22858945403696)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x14ca4479d0c0>>
    └ <Thread(task_queue, started daemon 22858945403696)>
  File "/usr/local/lib/python3.10/site-packages/flexget/task_queue.py", line 47, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x14ca4cd1a0e0>
    │    └ <flexget.task.Task object at 0x14ca41ac7070>
    └ <flexget.task_queue.TaskQueue object at 0x14ca4479d0c0>
  File "/usr/local/lib/python3.10/site-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x14ca41ac7070>
           └ <function Task.execute at 0x14ca4cd1a050>
  File "/usr/local/lib/python3.10/site-packages/flexget/task.py", line 727, in execute
    self._execute()
    │    └ <function Task._execute at 0x14ca4cd19fc0>
    └ <flexget.task.Task object at 0x14ca41ac7070>
  File "/usr/local/lib/python3.10/site-packages/flexget/task.py", line 696, in _execute
    self.__run_task_phase(phase)
    │                     └ 'output'
    └ <flexget.task.Task object at 0x14ca41ac7070>
  File "/usr/local/lib/python3.10/site-packages/flexget/task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x14ca41ac7070>, {'host': '192.168.2.240', 'port': 8081, 'use_ssl': False, 'username': 'admin',...
               │                 │       └ 'output'
               │                 └ <PluginInfo(name=qbittorrent_mod)>
               └ <flexget.task.Task object at 0x14ca41ac7070>
> File "/usr/local/lib/python3.10/site-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x14ca41ac7070>, {'host': '192.168.2.240', 'port': 8081, 'use_ssl': False, 'username': 'admin',...
             └ <Event(name=plugin.qbittorrent_mod.output,func=on_task_output,priority=135)>
  File "/usr/local/lib/python3.10/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x14ca41ac7070>, {'host': '192.168.2.240', 'port': 8081, 'use_ssl': False, 'username': 'admin',...
           │    └ <bound method PluginQBittorrentMod.on_task_output of <flexget.plugins.qbittorrent_mod.PluginQBittorrentMod object at 0x14ca46...
           └ <Event(name=plugin.qbittorrent_mod.output,func=on_task_output,priority=135)>

  File "/config/plugins/qbittorrent_mod.py", line 349, in on_task_output
    action(task, option)
    │      │     └ {'keeper': {'delete_files': True}}
    │      └ <flexget.task.Task object at 0x14ca41ac7070>
    └ <bound method PluginQBittorrentMod.remove_entries of <flexget.plugins.qbittorrent_mod.PluginQBittorrentMod object at 0x14ca46...

  File "/config/plugins/qbittorrent_mod.py", line 423, in remove_entries
    mode(task, option)
    │    │     └ {'delete_files': True}
    │    └ <flexget.task.Task object at 0x14ca41ac7070>
    └ <bound method PluginQBittorrentMod.remove_entries_keeper of <flexget.plugins.qbittorrent_mod.PluginQBittorrentMod object at 0...

  File "/config/plugins/qbittorrent_mod.py", line 447, in remove_entries_keeper
    keep_disk_space = keep_disk_space * 1024 * 1024 * 1024
                      └ None

TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "/config/plugins/qbittorrent_mod.py", line 349, in on_task_output
    action(task, option)
  File "/config/plugins/qbittorrent_mod.py", line 423, in remove_entries
    mode(task, option)
  File "/config/plugins/qbittorrent_mod.py", line 447, in remove_entries_keeper
    keep_disk_space = keep_disk_space * 1024 * 1024 * 1024
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

**Comment by madwind** [comment]
贴配置

**Comment by 2375399351** [comment]
#基础
  qbittorrent_base_template:
    qbittorrent_mod: *qbittorrent_setting
  #添加
  qbittorrent_add_template:
    qbittorrent_mod:
      action:
        add:
          #分类
          category: flexget
          #自动管理种子
          autoTMM: yes
          # 种子拒绝判断
          reject_on:
            #带宽
            bandwidth_limit: 13107200
            #当下载速度大于 bandwidth_limit * dl_speed 时 拒绝新种子
            dl_speed: 0.9
            #当限速低于 8MiB 时 拒绝新种子
            dl_limit: 9437184
            #设为yes可拒绝所有种子，一般清理数据库后使用防止添加未记录的老种
            all: no
  #删除
  qbittorrent_delete_keeper_template:
    qbittorrent_mod:
      action:
        remove:
          keeper:
            #删种同时数据
            delete_files: true
tasks:
  #自动删种
  delete:
    priority: 3
    #官方插件：disable 关闭任务记录 失败重试
    disable: [ seen, seen_info_hash, retry_failed, history ]
    #官方插件： if 过滤器
    if:
      #参考entry属性列表
      #种子在 Rss分类 并且 最后活动时间 < 2天 删除
      - qbittorrent_category in ['flexget'] and qbittorrent_last_activity < now - timedelta(days=2): accept
    #官方sort_by插件：按最后活动时间从早到晚排序 优先删除
    sort_by: qbittorrent_last_activity
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_delete_keeper_template

**Comment by madwind** [comment]
配置keep_disk_space

**Comment by 2375399351** [comment]
> 

好的，我试试看
