### ISSUE TITLE
U2签到过程中crash

### ISSUE THREAD

**Issue by vivodi** [IvonWei/flexget_qbittorrent_mod#58]
后来再次运行又没有问题了。crash的log如下：
```
2022-05-05 00:00:35 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         attempts: 0 / 5, url: https://u2.dmhy.org/image.php?action=adbc2&req=01fab842ed163b84022bca209c46abef12dc3651406a4dae9ddf3b069e7ce888d294f0493047109ba585ed9a70a94df4ae8345fc5ba17d68d4b812f4527d2b40ecc3a2cc0a2f9ce87175017c1b74a476
2022-05-05 00:00:36 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         request image...
2022-05-05 00:00:41 INFO     flexget.plugins.ptsites.utils.baidu_ocr sign_in         {'words_result': [{'words': 'TOEI VIDEO'}, {'words': '遊'}, {'words': '画'}, {'words': 'H'}, {'words': 'デヱルモンスクーズ'}, {'words': 'a/●e'}, {'words': 'HANB'}], 'words_result_num': 7, 'log_id': 1521882515317143009}
2022-05-05 00:00:41 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         original_ocr: 遊画デヱルモンスクーズ
2022-05-05 00:00:42 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         request image...
2022-05-05 00:00:44 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         request image...
2022-05-05 00:00:47 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         request image...
2022-05-05 00:00:49 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         request image...
2022-05-05 00:00:51 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         request image...
2022-05-05 00:00:53 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         request image...
2022-05-05 00:00:57 INFO     flexget.plugins.ptsites.utils.baidu_ocr sign_in         {'words_result': [{'words': 'TOEI VIOEO'}, {'words': 'M'}, {'words': '映画'}, {'words': 'H'}], 'words_result_num': 4, 'log_id': 1521882583657652784}
2022-05-05 00:00:59 INFO     flexget.plugins.ptsites.utils.baidu_ocr sign_in         {'words_result': [{'words': 'TOEI VIOEO'}, {'words': 'M'}], 'words_result_num': 2, 'log_id': 1521882591899123274}
2022-05-05 00:00:59 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         jap_ocr: 映画
2022-05-05 00:01:00 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         attempts: 1 / 5, url: https://u2.dmhy.org/image.php?action=adbc2&req=aa1150f0e3ef9fb624eba92dbe3217fa37c7c127a6992e104b6a528f7e0d2be29a660a8d54d9ea8142c3ec0a7dd36f4d3cab1f1c75b3db60302e3e441b262d3aac495925aec70ca833385a4f519d831c
2022-05-05 00:01:01 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         request image...
2022-05-05 00:01:04 INFO     flexget.plugins.ptsites.utils.baidu_ocr sign_in         {'words_result': [{'words': 'す3'}], 'words_result_num': 1, 'log_id': 1521882609338183602}
2022-05-05 00:01:04 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         original_ocr: す
2022-05-05 00:01:04 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         attempts: 2 / 5, url: https://u2.dmhy.org/image.php?action=adbc2&req=94ff44a3641899a93d1550fffff5b49e4ee61d648c87522cbbed7b7189d03a070ef7541dbcb888ce2be1dad2389d1d7af118ead612d04d97f94fb54597d9b5ed49ea3c18a2c129f1c939d1f5e79df5de
2022-05-05 00:01:05 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         request image...
2022-05-05 00:01:08 INFO     flexget.plugins.ptsites.utils.baidu_ocr sign_in         {'words_result': [{'words': '电r'}, {'words': 'E'}, {'words': '進レ'}], 'words_result_num': 3, 'log_id': 1521882627010633788}
2022-05-05 00:01:08 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         original_ocr: 电進レ
2022-05-05 00:01:09 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         request image...
2022-05-05 00:01:11 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         request image...
2022-05-05 00:01:13 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         request image...
2022-05-05 00:01:15 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         request image...
2022-05-05 00:01:17 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         request image...
2022-05-05 00:01:19 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         request image...
2022-05-05 00:01:21 DEBUG    flexget.plugins.ptsites.sites.dmhy sign_in         request image...
2022-05-05 00:02:23 INFO     flexget.plugins.ptsites.utils.baidu_ocr sign_in         {'error_code': 'SDK108', 'error_msg': 'connection or read data timeout'}
2022-05-05 00:02:23 DEBUG    entry         sign_in         Marking entry 'dmhy 2022-05-05' as failed
2022-05-05 00:02:23 ERROR    entry         sign_in         Failed dmhy 2022-05-05 (Sign_in=> connection or read data timeout)
2022-05-05 00:02:23 DEBUG    failed        sign_in         Marking dmhy 2022-05-05 in failed list. Has failed 1 times.
2022-05-05 00:02:23 DEBUG    backlog       sign_in         Saving dmhy 2022-05-05
2022-05-05 00:02:23 DEBUG    task          sign_in         Plugin retry_failed has requested task to be ran again after execution has completed.
2022-05-05 00:02:23 VERBOSE  task          sign_in         FAILED: `dmhy 2022-05-05` by auto_sign_in plugin because sign_in=> connection or read data timeout
2022-05-05 00:02:25 INFO     flexget.plugins.ptsites.utils.baidu_ocr sign_in         {'words_result': [{'words': '电'}, {'words': 'DVD'}, {'words': 'EE'}, {'words': '進ル'}], 'words_result_num': 4, 'log_id': 1521882949696491875}
2022-05-05 00:02:25 CRITICAL task          sign_in         BUG: Unhandled error in plugin auto_sign_in: object of type 'NoneType' has no len()
Traceback (most recent call last):

  File "/usr/lib/python3.10/threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe3bde588b0>
    └ <Thread(task_queue, started daemon 140615910708800)>
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe3bde585e0>
    └ <Thread(task_queue, started daemon 140615910708800)>
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 140615910708800)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 140615910708800)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7fe3b1923580>>
    └ <Thread(task_queue, started daemon 140615910708800)>
  File "/usr/local/lib/python3.10/dist-packages/flexget/task_queue.py", line 47, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x7fe3bab2b640>
    │    └ <flexget.task.Task object at 0x7fe3b19efd90>
    └ <flexget.task_queue.TaskQueue object at 0x7fe3b1923580>
  File "/usr/local/lib/python3.10/dist-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x7fe3b19efd90>
           └ <function Task.execute at 0x7fe3bab2b5b0>
  File "/usr/local/lib/python3.10/dist-packages/flexget/task.py", line 727, in execute
    self._execute()
    │    └ <function Task._execute at 0x7fe3bab2b520>
    └ <flexget.task.Task object at 0x7fe3b19efd90>
  File "/usr/local/lib/python3.10/dist-packages/flexget/task.py", line 696, in _execute
    self.__run_task_phase(phase)
    │                     └ 'output'
    └ <flexget.task.Task object at 0x7fe3b19efd90>
  File "/usr/local/lib/python3.10/dist-packages/flexget/task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x7fe3b19efd90>, {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (...
               │                 │       └ 'output'
               │                 └ <PluginInfo(name=auto_sign_in)>
               └ <flexget.task.Task object at 0x7fe3b19efd90>
> File "/usr/local/lib/python3.10/dist-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x7fe3b19efd90>, {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (...
             └ <Event(name=plugin.auto_sign_in.output,func=on_task_output,priority=128)>
  File "/usr/local/lib/python3.10/dist-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x7fe3b19efd90>, {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (...
           │    └ <bound method PluginAutoSignIn.on_task_output of <flexget.plugins.auto_sign_in.PluginAutoSignIn object at 0x7fe3b3c26440>>
           └ <Event(name=plugin.auto_sign_in.output,func=on_task_output,priority=128)>

  File "/root/.flexget/plugins/auto_sign_in.py", line 77, in on_task_output
    Executor.sign_in(entry, config)
    │        │       │      └ {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/...
    │        │       └ <Entry(title=dmhy 2022-05-05,state=failed)>
    │        └ <staticmethod(<function Executor.sign_in at 0x7fe3ba734670>)>
    └ <class 'flexget.plugins.ptsites.executor.Executor'>

  File "/root/.flexget/plugins/ptsites/executor.py", line 61, in sign_in
    site_object.sign_in(entry, config)
    │           │       │      └ {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/...
    │           │       └ <Entry(title=dmhy 2022-05-05,state=failed)>
    │           └ <function SiteBase.sign_in at 0x7fe3ba72bbe0>
    └ <flexget.plugins.ptsites.sites.dmhy.MainClass object at 0x7fe3b0663df0>

  File "/root/.flexget/plugins/ptsites/schema/site_base.py", line 112, in sign_in
    last_response = method(entry, config, work, last_content)
                    │      │      │       │     └ '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<...
                    │      │      │       └ <flexget.plugins.ptsites.schema.site_base.Work object at 0x7fe3b3e534c0>
                    │      │      └ {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/...
                    │      └ <Entry(title=dmhy 2022-05-05,state=failed)>
                    └ <bound method MainClass.sign_in_by_anime of <flexget.plugins.ptsites.sites.dmhy.MainClass object at 0x7fe3b0663df0>>

  File "/root/.flexget/plugins/ptsites/sites/dmhy.py", line 116, in sign_in_by_anime
    data = self.build_data(entry, config, work, last_content, ocr_config)
           │    │          │      │       │     │             └ {'retry': 5, 'char_count': 3, 'score': 30}
           │    │          │      │       │     └ '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<...
           │    │          │      │       └ <flexget.plugins.ptsites.schema.site_base.Work object at 0x7fe3b3e534c0>
           │    │          │      └ {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/...
           │    │          └ <Entry(title=dmhy 2022-05-05,state=failed)>
           │    └ <function MainClass.build_data at 0x7fe3ba30bbe0>
           └ <flexget.plugins.ptsites.sites.dmhy.MainClass object at 0x7fe3b0663df0>

  File "/root/.flexget/plugins/ptsites/sites/dmhy.py", line 189, in build_data
    return self.build_data(entry, config, work, reload_content, ocr_config)
           │    │          │      │       │     │               └ {'retry': 5, 'char_count': 3, 'score': 30}
           │    │          │      │       │     └ '<div id="showup"><table class="captcha"><tr>\n\t<td><img src="image.php?action=adbc2&req=aa1150f0e3ef9fb624eba92dbe3217fa37c...
           │    │          │      │       └ <flexget.plugins.ptsites.schema.site_base.Work object at 0x7fe3b3e534c0>
           │    │          │      └ {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/...
           │    │          └ <Entry(title=dmhy 2022-05-05,state=failed)>
           │    └ <function MainClass.build_data at 0x7fe3ba30bbe0>
           └ <flexget.plugins.ptsites.sites.dmhy.MainClass object at 0x7fe3b0663df0>

  File "/root/.flexget/plugins/ptsites/sites/dmhy.py", line 189, in build_data
    return self.build_data(entry, config, work, reload_content, ocr_config)
           │    │          │      │       │     │               └ {'retry': 5, 'char_count': 3, 'score': 30}
           │    │          │      │       │     └ '<div id="showup"><table class="captcha"><tr>\n\t<td><img src="image.php?action=adbc2&req=94ff44a3641899a93d1550fffff5b49e4ee...
           │    │          │      │       └ <flexget.plugins.ptsites.schema.site_base.Work object at 0x7fe3b3e534c0>
           │    │          │      └ {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/...
           │    │          └ <Entry(title=dmhy 2022-05-05,state=failed)>
           │    └ <function MainClass.build_data at 0x7fe3ba30bbe0>
           └ <flexget.plugins.ptsites.sites.dmhy.MainClass object at 0x7fe3b0663df0>

  File "/root/.flexget/plugins/ptsites/sites/dmhy.py", line 140, in build_data
    oct_text = ocr_text1 if len(ocr_text1) > len(ocr_text2) else ocr_text2
               │                │                │               └ '电進ル'
               │                │                └ '电進ル'
               │                └ None
               └ None

TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "/root/.flexget/plugins/auto_sign_in.py", line 77, in on_task_output
    Executor.sign_in(entry, config)
  File "/root/.flexget/plugins/ptsites/executor.py", line 61, in sign_in
    site_object.sign_in(entry, config)
  File "/root/.flexget/plugins/ptsites/schema/site_base.py", line 112, in sign_in
    last_response = method(entry, config, work, last_content)
  File "/root/.flexget/plugins/ptsites/sites/dmhy.py", line 116, in sign_in_by_anime
    data = self.build_data(entry, config, work, last_content, ocr_config)
  File "/root/.flexget/plugins/ptsites/sites/dmhy.py", line 189, in build_data
    return self.build_data(entry, config, work, reload_content, ocr_config)
  File "/root/.flexget/plugins/ptsites/sites/dmhy.py", line 189, in build_data
    return self.build_data(entry, config, work, reload_content, ocr_config)
  File "/root/.flexget/plugins/ptsites/sites/dmhy.py", line 140, in build_data
    oct_text = ocr_text1 if len(ocr_text1) > len(ocr_text2) else ocr_text2
TypeError: object of type 'NoneType' has no len()
```

**Comment by madwind** [comment]
看来来是ocr的连接错误 已处理
