### ISSUE TITLE
flexget 启动加载插件报错 Plugin `flexget.plugins.telegram_mod` failed to import dependencies

### ISSUE THREAD

**Issue by vivagonna** [IvonWei/flexget_qbittorrent_mod#9]
环境是群晖docker和wiserain/flexget最新镜像

2021-06-03 19:44:31 DEBUG    manager                       Config file /config/config.yml selected
2021-06-03 19:44:31 DEBUG    manager                       sys.defaultencoding: utf-8
2021-06-03 19:44:31 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2021-06-03 19:44:31 DEBUG    manager                       flexget detected io encoding: utf-8
2021-06-03 19:44:31 DEBUG    manager                       os.path.supports_unicode_filenames: False
2021-06-03 19:44:31 DEBUG    plugin                        Trying to load plugins from: ['/config/plugins', '/usr/lib/python3.8/site-packages/flexget/plugins']
2021-06-03 19:44:31 CRITICAL plugin                        Plugin `flexget.plugins.telegram_mod` failed to import dependencies
Traceback (most recent call last):

  File "/usr/bin/flexget", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7f48805fa9d0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/lib/python3.8/site-packages/flexget/__init__.py", line 44, in main
    manager.start()
    │       └ <function Manager.start at 0x7f487d91a040>
    └ <flexget.manager.Manager object at 0x7f487d905e20>
  File "/usr/lib/python3.8/site-packages/flexget/manager.py", line 383, in start
    self.initialize()
    │    └ <function Manager.initialize at 0x7f487d915dc0>
    └ <flexget.manager.Manager object at 0x7f487d905e20>
  File "/usr/lib/python3.8/site-packages/flexget/manager.py", line 223, in initialize
    plugin.load_plugins(
    │      └ <function load_plugins at 0x7f487dd363a0>
    └ <module 'flexget.plugin' from '/usr/lib/python3.8/site-packages/flexget/plugin.py'>
  File "/usr/lib/python3.8/site-packages/flexget/plugin.py", line 550, in load_plugins
    _load_plugins_from_dirs(extra_plugins)
    │                       └ ['/config/plugins', '/usr/lib/python3.8/site-packages/flexget/plugins']
    └ <function _load_plugins_from_dirs at 0x7f487dd361f0>
  File "/usr/lib/python3.8/site-packages/flexget/plugin.py", line 468, in _load_plugins_from_dirs
    _import_plugin(module_name, plugin_path)
    │              │            └ PosixPath('/config/plugins/telegram_mod.py')
    │              └ 'flexget.plugins.telegram_mod'
    └ <function _import_plugin at 0x7f487dd36160>
> File "/usr/lib/python3.8/site-packages/flexget/plugin.py", line 419, in _import_plugin
    import_module(module_name)
    │             └ 'flexget.plugins.telegram_mod'
    └ <function import_module at 0x7f48806f5790>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'flexget.plugins.telegram_mod'
           │          └ <function _gcd_import at 0x7f48808a4430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/config/plugins/telegram_mod.py", line 3, in <module>
    from PIL import Image

ModuleNotFoundError: No module named 'PIL'
2021-06-03 19:44:31 ERROR    flexget.plugins.ptsites.utils.cfscrapewrapper                 Error importing pyppeteer: No module named 'pyppeteer'
2021-06-03 19:44:31 CRITICAL plugin                        Plugin `flexget.plugins.auto_sign_in` failed to import dependencies
Traceback (most recent call last):

  File "/usr/bin/flexget", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7f48805fa9d0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/lib/python3.8/site-packages/flexget/__init__.py", line 44, in main
    manager.start()
    │       └ <function Manager.start at 0x7f487d91a040>
    └ <flexget.manager.Manager object at 0x7f487d905e20>
  File "/usr/lib/python3.8/site-packages/flexget/manager.py", line 383, in start
    self.initialize()
    │    └ <function Manager.initialize at 0x7f487d915dc0>
    └ <flexget.manager.Manager object at 0x7f487d905e20>
  File "/usr/lib/python3.8/site-packages/flexget/manager.py", line 223, in initialize
    plugin.load_plugins(
    │      └ <function load_plugins at 0x7f487dd363a0>
    └ <module 'flexget.plugin' from '/usr/lib/python3.8/site-packages/flexget/plugin.py'>
  File "/usr/lib/python3.8/site-packages/flexget/plugin.py", line 550, in load_plugins
    _load_plugins_from_dirs(extra_plugins)
    │                       └ ['/config/plugins', '/usr/lib/python3.8/site-packages/flexget/plugins']
    └ <function _load_plugins_from_dirs at 0x7f487dd361f0>
  File "/usr/lib/python3.8/site-packages/flexget/plugin.py", line 468, in _load_plugins_from_dirs
    _import_plugin(module_name, plugin_path)
    │              │            └ PosixPath('/config/plugins/auto_sign_in.py')
    │              └ 'flexget.plugins.auto_sign_in'
    └ <function _import_plugin at 0x7f487dd36160>
> File "/usr/lib/python3.8/site-packages/flexget/plugin.py", line 419, in _import_plugin
    import_module(module_name)
    │             └ 'flexget.plugins.auto_sign_in'
    └ <function import_module at 0x7f48806f5790>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'flexget.plugins.auto_sign_in'
           │          └ <function _gcd_import at 0x7f48808a4430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/config/plugins/auto_sign_in.py", line 9, in <module>
    from .ptsites.utils.details_report import DetailsReport

  File "/config/plugins/ptsites/utils/details_report.py", line 4, in <module>
    from PIL import Image, ImageDraw, ImageFont

ModuleNotFoundError: No module named 'PIL'
2021-06-03 19:44:31 INFO     flexget.plugins.ptsites._version                 flexget_qbittorrent_mod v0.8.8_dev
2021-06-03 19:44:31 CRITICAL plugin                        Plugin `flexget.plugins.ptsites.utils.details_report` failed to import dependencies
Traceback (most recent call last):

  File "/usr/bin/flexget", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7f48805fa9d0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/lib/python3.8/site-packages/flexget/__init__.py", line 44, in main
    manager.start()
    │       └ <function Manager.start at 0x7f487d91a040>
    └ <flexget.manager.Manager object at 0x7f487d905e20>
  File "/usr/lib/python3.8/site-packages/flexget/manager.py", line 383, in start
    self.initialize()
    │    └ <function Manager.initialize at 0x7f487d915dc0>
    └ <flexget.manager.Manager object at 0x7f487d905e20>
  File "/usr/lib/python3.8/site-packages/flexget/manager.py", line 223, in initialize
    plugin.load_plugins(
    │      └ <function load_plugins at 0x7f487dd363a0>
    └ <module 'flexget.plugin' from '/usr/lib/python3.8/site-packages/flexget/plugin.py'>
  File "/usr/lib/python3.8/site-packages/flexget/plugin.py", line 550, in load_plugins
    _load_plugins_from_dirs(extra_plugins)
    │                       └ ['/config/plugins', '/usr/lib/python3.8/site-packages/flexget/plugins']
    └ <function _load_plugins_from_dirs at 0x7f487dd361f0>
  File "/usr/lib/python3.8/site-packages/flexget/plugin.py", line 468, in _load_plugins_from_dirs
    _import_plugin(module_name, plugin_path)
    │              │            └ PosixPath('/config/plugins/ptsites/utils/details_report.py')
    │              └ 'flexget.plugins.ptsites.utils.details_report'
    └ <function _import_plugin at 0x7f487dd36160>
> File "/usr/lib/python3.8/site-packages/flexget/plugin.py", line 419, in _import_plugin
    import_module(module_name)
    │             └ 'flexget.plugins.ptsites.utils.details_report'
    └ <function import_module at 0x7f48806f5790>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'flexget.plugins.ptsites.utils.details_report'
           │          └ <function _gcd_import at 0x7f48808a4430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/config/plugins/ptsites/utils/details_report.py", line 4, in <module>
    from PIL import Image, ImageDraw, ImageFont

ModuleNotFoundError: No module named 'PIL'
2021-06-03 19:44:31 CRITICAL plugin                        Plugin `flexget.plugins.ptsites.utils.dmhy_image` failed to import dependencies
Traceback (most recent call last):

  File "/usr/bin/flexget", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7f48805fa9d0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/lib/python3.8/site-packages/flexget/__init__.py", line 44, in main
    manager.start()
    │       └ <function Manager.start at 0x7f487d91a040>
    └ <flexget.manager.Manager object at 0x7f487d905e20>
  File "/usr/lib/python3.8/site-packages/flexget/manager.py", line 383, in start
    self.initialize()
    │    └ <function Manager.initialize at 0x7f487d915dc0>
    └ <flexget.manager.Manager object at 0x7f487d905e20>
  File "/usr/lib/python3.8/site-packages/flexget/manager.py", line 223, in initialize
    plugin.load_plugins(
    │      └ <function load_plugins at 0x7f487dd363a0>
    └ <module 'flexget.plugin' from '/usr/lib/python3.8/site-packages/flexget/plugin.py'>
  File "/usr/lib/python3.8/site-packages/flexget/plugin.py", line 550, in load_plugins
    _load_plugins_from_dirs(extra_plugins)
    │                       └ ['/config/plugins', '/usr/lib/python3.8/site-packages/flexget/plugins']
    └ <function _load_plugins_from_dirs at 0x7f487dd361f0>
  File "/usr/lib/python3.8/site-packages/flexget/plugin.py", line 468, in _load_plugins_from_dirs
    _import_plugin(module_name, plugin_path)
    │              │            └ PosixPath('/config/plugins/ptsites/utils/dmhy_image.py')
    │              └ 'flexget.plugins.ptsites.utils.dmhy_image'
    └ <function _import_plugin at 0x7f487dd36160>
> File "/usr/lib/python3.8/site-packages/flexget/plugin.py", line 419, in _import_plugin
    import_module(module_name)
    │             └ 'flexget.plugins.ptsites.utils.dmhy_image'
    └ <function import_module at 0x7f48806f5790>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'flexget.plugins.ptsites.utils.dmhy_image'
           │          └ <function _gcd_import at 0x7f48808a4430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/config/plugins/ptsites/utils/dmhy_image.py", line 1, in <module>
    from PIL import ImageChops, Image

ModuleNotFoundError: No module named 'PIL'
2021-06-03 19:44:31 CRITICAL plugin                        Plugin `flexget.plugins.ptsites.sites.dmhy` failed to import dependencies
Traceback (most recent call last):

  File "/usr/bin/flexget", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7f48805fa9d0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/lib/python3.8/site-packages/flexget/__init__.py", line 44, in main
    manager.start()
    │       └ <function Manager.start at 0x7f487d91a040>
    └ <flexget.manager.Manager object at 0x7f487d905e20>
  File "/usr/lib/python3.8/site-packages/flexget/manager.py", line 383, in start
    self.initialize()
    │    └ <function Manager.initialize at 0x7f487d915dc0>
    └ <flexget.manager.Manager object at 0x7f487d905e20>
  File "/usr/lib/python3.8/site-packages/flexget/manager.py", line 223, in initialize
    plugin.load_plugins(
    │      └ <function load_plugins at 0x7f487dd363a0>
    └ <module 'flexget.plugin' from '/usr/lib/python3.8/site-packages/flexget/plugin.py'>
  File "/usr/lib/python3.8/site-packages/flexget/plugin.py", line 550, in load_plugins
    _load_plugins_from_dirs(extra_plugins)
    │                       └ ['/config/plugins', '/usr/lib/python3.8/site-packages/flexget/plugins']
    └ <function _load_plugins_from_dirs at 0x7f487dd361f0>
  File "/usr/lib/python3.8/site-packages/flexget/plugin.py", line 468, in _load_plugins_from_dirs
    _import_plugin(module_name, plugin_path)
    │              │            └ PosixPath('/config/plugins/ptsites/sites/dmhy.py')
    │              └ 'flexget.plugins.ptsites.sites.dmhy'
    └ <function _import_plugin at 0x7f487dd36160>
> File "/usr/lib/python3.8/site-packages/flexget/plugin.py", line 419, in _import_plugin
    import_module(module_name)
    │             └ 'flexget.plugins.ptsites.sites.dmhy'
    └ <function import_module at 0x7f48806f5790>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'flexget.plugins.ptsites.sites.dmhy'
           │          └ <function _gcd_import at 0x7f48808a4430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/config/plugins/ptsites/sites/dmhy.py", line 21, in <module>
    from ..utils.dmhy_image import DmhyImage

  File "/config/plugins/ptsites/utils/dmhy_image.py", line 1, in <module>
    from PIL import ImageChops, Image

ModuleNotFoundError: No module named 'PIL'

尝试在容器内手动安装pillow 报错 __main__.RequiredDependencyException: zlib

**Comment by madwind** [comment]
请使用 madwind/flexget 镜像，需要自建可以参考 image-builder\Dockerfile
